services:
    container:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        tty: true
        volumes:
            - .:/workspace
            - react_node_modules:/workspace/node_modules
        ports:
            - 3000:3000
volumes:
    react_node_modules:
